#!/bin/bash

set -e

cd "$(dirname "$0")/../builtinFonts"

echo "// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh"
echo "#pragma once"
echo ""

echo "#define SOURCESERIF_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./sourceserif_12_regular.h",
  "./sourceserif_12_bold.h",
  "./sourceserif_12_bolditalic.h",
  "./sourceserif_12_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define SOURCESERIF_14_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./sourceserif_14_regular.h",
  "./sourceserif_14_bold.h",
  "./sourceserif_14_bolditalic.h",
  "./sourceserif_14_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define SOURCESERIF_16_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./sourceserif_16_regular.h",
  "./sourceserif_16_bold.h",
  "./sourceserif_16_bolditalic.h",
  "./sourceserif_16_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define SOURCESERIF_18_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./sourceserif_18_regular.h",
  "./sourceserif_18_bold.h",
  "./sourceserif_18_bolditalic.h",
  "./sourceserif_18_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define SOURCESANS_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./sourcesans_12_regular.h",
  "./sourcesans_12_bold.h",
  "./sourcesans_12_bolditalic.h",
  "./sourcesans_12_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define SOURCESANS_14_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./sourcesans_14_regular.h",
  "./sourcesans_14_bold.h",
  "./sourcesans_14_bolditalic.h",
  "./sourcesans_14_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define SOURCESANS_16_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./sourcesans_16_regular.h",
  "./sourcesans_16_bold.h",
  "./sourcesans_16_bolditalic.h",
  "./sourcesans_16_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define SOURCESANS_18_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./sourcesans_18_regular.h",
  "./sourcesans_18_bold.h",
  "./sourcesans_18_bolditalic.h",
  "./sourcesans_18_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define UI_10_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./inter_10_regular.h",
  "./inter_10_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define UI_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./inter_12_regular.h",
  "./inter_12_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define SMALL_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./inter_8_regular.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo ""
echo "// Font ID 0 is reserved as the \"not found\" sentinel."
echo "// Guard against any hash accidentally producing 0."
for font_id in \
  SOURCESERIF_12_FONT_ID SOURCESERIF_14_FONT_ID SOURCESERIF_16_FONT_ID SOURCESERIF_18_FONT_ID \
  SOURCESANS_12_FONT_ID SOURCESANS_14_FONT_ID SOURCESANS_16_FONT_ID SOURCESANS_18_FONT_ID \
  UI_10_FONT_ID UI_12_FONT_ID SMALL_FONT_ID; do
  echo "static_assert(${font_id} != 0, \"Font ID collision with sentinel\");"
done
