#pragma once

#include <builtinFonts/sourceserif_12_bold.h>
#include <builtinFonts/sourceserif_12_bolditalic.h>
#include <builtinFonts/sourceserif_12_italic.h>
#include <builtinFonts/sourceserif_12_regular.h>
#include <builtinFonts/sourceserif_14_bold.h>
#include <builtinFonts/sourceserif_14_bolditalic.h>
#include <builtinFonts/sourceserif_14_italic.h>
#include <builtinFonts/sourceserif_14_regular.h>
#include <builtinFonts/sourceserif_16_bold.h>
#include <builtinFonts/sourceserif_16_bolditalic.h>
#include <builtinFonts/sourceserif_16_italic.h>
#include <builtinFonts/sourceserif_16_regular.h>
#include <builtinFonts/sourceserif_18_bold.h>
#include <builtinFonts/sourceserif_18_bolditalic.h>
#include <builtinFonts/sourceserif_18_italic.h>
#include <builtinFonts/sourceserif_18_regular.h>
#include <builtinFonts/inter_8_regular.h>
#include <builtinFonts/inter_10_bold.h>
#include <builtinFonts/inter_10_regular.h>
#include <builtinFonts/inter_12_bold.h>
#include <builtinFonts/inter_12_regular.h>
#include <builtinFonts/sourcesans_12_bold.h>
#include <builtinFonts/sourcesans_12_bolditalic.h>
#include <builtinFonts/sourcesans_12_italic.h>
#include <builtinFonts/sourcesans_12_regular.h>
#include <builtinFonts/sourcesans_14_bold.h>
#include <builtinFonts/sourcesans_14_bolditalic.h>
#include <builtinFonts/sourcesans_14_italic.h>
#include <builtinFonts/sourcesans_14_regular.h>
#include <builtinFonts/sourcesans_16_bold.h>
#include <builtinFonts/sourcesans_16_bolditalic.h>
#include <builtinFonts/sourcesans_16_italic.h>
#include <builtinFonts/sourcesans_16_regular.h>
#include <builtinFonts/sourcesans_18_bold.h>
#include <builtinFonts/sourcesans_18_bolditalic.h>
#include <builtinFonts/sourcesans_18_italic.h>
#include <builtinFonts/sourcesans_18_regular.h>
