// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define NOTOSERIF_12_FONT_ID (-415753331)
#define NOTOSERIF_14_FONT_ID (-816182985)
#define NOTOSERIF_16_FONT_ID (1182310739)
#define NOTOSERIF_18_FONT_ID (1511702731)
#define NOTOSANS_12_FONT_ID (665762675)
#define NOTOSANS_14_FONT_ID (-1296836405)
#define NOTOSANS_16_FONT_ID (-1137983621)
#define NOTOSANS_18_FONT_ID (-1165085658)
#define UI_10_FONT_ID (-1489209935)
#define UI_12_FONT_ID (1151501202)
#define SMALL_FONT_ID (1097870400)

// Font ID 0 is reserved as the "not found" sentinel.
// Guard against any hash accidentally producing 0.
static_assert(NOTOSERIF_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SMALL_FONT_ID != 0, "Font ID collision with sentinel");
