// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define SOURCESERIF_12_FONT_ID (-1115179355)
#define SOURCESERIF_14_FONT_ID (2140194181)
#define SOURCESERIF_16_FONT_ID (1664355516)
#define SOURCESERIF_18_FONT_ID (-1227572204)
#define SOURCESANS_12_FONT_ID (23289327)
#define SOURCESANS_14_FONT_ID (1257960495)
#define SOURCESANS_16_FONT_ID (-1771853600)
#define SOURCESANS_18_FONT_ID (-671841978)
#define UI_10_FONT_ID (-1489209935)
#define UI_12_FONT_ID (1151501202)
#define SMALL_FONT_ID (1097870400)

// Font ID 0 is reserved as the "not found" sentinel.
// Guard against any hash accidentally producing 0.
static_assert(SOURCESERIF_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SOURCESERIF_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SOURCESERIF_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SOURCESERIF_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SOURCESANS_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SOURCESANS_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SOURCESANS_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SOURCESANS_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SMALL_FONT_ID != 0, "Font ID collision with sentinel");
