// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define NOTOSERIF_12_FONT_ID (583844403)
#define NOTOSERIF_14_FONT_ID (-1939845523)
#define NOTOSERIF_16_FONT_ID (-440472387)
#define NOTOSERIF_18_FONT_ID (-1567951456)
#define NOTOSANS_12_FONT_ID (634992850)
#define NOTOSANS_14_FONT_ID (271118525)
#define NOTOSANS_16_FONT_ID (-863774302)
#define NOTOSANS_18_FONT_ID (360233193)
#define UI_10_FONT_ID (-1489209935)
#define UI_12_FONT_ID (1151501202)
#define SMALL_FONT_ID (1097870400)

// Font ID 0 is reserved as the "not found" sentinel.
// Guard against any hash accidentally producing 0.
static_assert(NOTOSERIF_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SMALL_FONT_ID != 0, "Font ID collision with sentinel");
